[package]
name = "crossfeed-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
crossfeed-net = { path = "../crossfeed-net" }
regex = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"

[dev-dependencies]
assert_matches = "1"
