[package]
name = "crossfeed-web"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1"
http = "1"
rand = "0.8"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"

[dev-dependencies]
assert_matches = "1"
