[package]
name = "crossfeed-ingest"
version = "0.1.0"
edition = "2024"

[dependencies]
crossfeed-proxy = { path = "../crossfeed-proxy" }
crossfeed-storage = { path = "../crossfeed-storage" }
futures = "0.3"
