[package]
name = "crossfeed-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
crossfeed-storage = { path = "../crossfeed-storage" }
dirs = "5.0"
iced = "0.13"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
